CC = gcc
SDL_PATH = C:\Users\Preeti Bisht\OneDrive\Desktop\SDL2-devel-2.32.10-mingw\SDL2-2.32.10\x86_64-w64-mingw32
INCLUDE_DIRS = -Iinclude -I$(SDL_PATH)/include
LIB_DIRS = -L$(SDL_PATH)/lib
CFLAGS = $(LIB_DIRS) -lmingw32 -lSDL2main -lSDL2
SRC = src\main.c
TARGET = game.exe

$(TARGET): $(SRC)
$(CC) $(CFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS)

run : $(TARGET)
./$(TARGET)

Clean :
del $(TARGET)